### ISSUE TITLE
add compatibility with `with: GITHUB_TOKEN: { secret.GITHUB_TOKEN }`

### ISSUE THREAD

**Issue by gr2m** [octokit/action.js#20]
The current documentation shows examples that pass `secret.GITHUB_TOKEN` into the `with` input parameters, instead of setting environment variables

https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#using-the-github_token-in-a-workflow

`@octokit/actions` should work with both

```yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

as well as

```yml
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

The parameters passed in the `with:` object are turned into environment variables internally, with an `INPUT_` prefix

**Comment by copperwall** [comment]
Hey @gr2m 👋 I think this issue was resolved in octokit/auth-action.js https://github.com/octokit/auth-action.js/pull/11

**Comment by gr2m** [comment]
That's right, thank you!
