### ISSUE TITLE
Node deprecation warning

### ISSUE THREAD

**Issue by olivercodes** [octokit/action.js#414]
Similar/same as https://github.com/actions/github-script/issues/202, when using latest version of @octokit/action, we get the following in our Github actions console:

```
(node:1578) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
```

This is coming from proxy-agent, as hashicorp ran into the same problem and fixed it here:

https://github.com/hashicorp/js-releases/pull/43

**Comment by gr2m** [comment]
a pull request would be much appreciated
