### ISSUE TITLE
Depreaction Warning :Buffer is deprecated due to security and usability issues

### ISSUE THREAD

**Issue by DeeptimayeeSethi** [octokit/action.js#430]
We are using GitHub Actions for a pull request workflow , and We are getting below error in the PR-Process set up . Is it related to octokit ? Can someone help on this

![error in PR](https://user-images.githubusercontent.com/64842528/190351581-ebdafa4f-1d33-4a20-815e-08aca7233a50.PNG)

Also attaching raw logs
[Uploading error raw logs.txt…]()

**Comment by timrogers** [comment]
Hi there! 👋🏻 Are you able to share those logs? The attachment is missing. It would also be great to see the Actions workflow file if you're able to share.

**Comment by DeeptimayeeSethi** [comment]
here is the workflow file
[workflow.txt](https://github.com/octokit/action.js/files/9576032/workflow.txt)

also attaching the raw logs
[error raw logs.txt](https://github.com/octokit/action.js/files/9576035/error.raw.logs.txt)

**Comment by wolfy1339** [comment]
This should have been fixed in #425

**Comment by timrogers** [comment]
@DeeptimayeeSethi Can you check which version of the package you're using in your `package-lock.json`?

**Comment by DeeptimayeeSethi** [comment]
I copied whole content in the text file
[package-lock.txt](https://github.com/octokit/action.js/files/9580652/package-lock.txt)

**Comment by DeeptimayeeSethi** [comment]
@wolfy1339 , the changes to resolve the issue has been done related to proxy agent. However, we are not using proxy, but using universal -user-agent. Any suggestions.

**Comment by DeeptimayeeSethi** [comment]
@timrogers , I copied whole content in the text file
[package-lock.txt](https://github.com/octokit/action.js/files/9605352/package-lock.txt)

Is there a way to synch up with you or call with you , to understand the issue

**Comment by timrogers** [comment]
Hi @DeeptimayeeSethi! 👋🏻 Just to confirm, is the issue here the Deprecation Warning itself? Or is it the "Not Found" branch? If the latter is what you're really worried about, that isn't related to the deprecation warning.

**Comment by DeeptimayeeSethi** [comment]
@timrogers , The issue is with deprecation warning, sharing the error screenshot. You asked me about package-lock version. Does it has something to do with teh error we are getting? 
Can you help me find out?

![error in PR](https://user-images.githubusercontent.com/64842528/191443846-c37cb3b4-4c82-4c27-8fe4-7f50aa846ca1.PNG)

**Comment by timrogers** [comment]
Hi @DeeptimayeeSethi! Sorry for the delay in getting back to you. Looking at your `package-lock.json` and workflow file, it doesn't look like you are actually using this package:

```
const core = require('@actions/core');
const github = require('@actions/github');
```

Would you be able to create an issue on the relevant one of those repos?

**Comment by wolfy1339** [comment]
This issue is over 2 years old and with no response from the actual author
