### ISSUE TITLE
[BUG]: `@octokit/action` 5.0.3 has no type definition

### ISSUE THREAD

**Issue by kitsuyui** [octokit/action.js#493]
### What happened?

The npm package of `@octokit/action` 5.0.3 released does not contain type definition files.
The following shows the comparison with the files of 5.0.2.

5.0.2: https://www.npmjs.com/package/@octokit/action/v/5.0.2?activeTab=code
5.0.3 https://www.npmjs.com/package/@octokit/action/v/5.0.3?activeTab=code

<img width="784" alt="5-0-2-dist-node" src="https://github.com/octokit/action.js/assets/2596972/87462bb4-f6b3-4412-96cd-c67541b924d3">
<img width="793" alt="5-0-2" src="https://github.com/octokit/action.js/assets/2596972/8b34ac0b-a2af-4cda-be4f-70d004211501">
<img width="790" alt="5-0-3-dist-node" src="https://github.com/octokit/action.js/assets/2596972/3535e635-004e-4616-bdd6-a096a0942748">
<img width="790" alt="5-0-3" src="https://github.com/octokit/action.js/assets/2596972/d8c2528f-db14-463b-9c8d-e8f88c6c4fad">

### Versions

`@octokit/action` 5.0.3

### Relevant log output

Since there is no type definition, an error occurs during build.
The following is an example of a build in my project https://github.com/kitsuyui/happy-commit/pull/95 .

`import { Octokit } from '@octokit/action';`

```shell
yarn run v1.22.19
$ ncc build src/index.ts --license licenses.txt
ncc: Version 0.36.1
ncc: Compiling file index.js into CJS
ncc: Using typescript@5.0.4 (local user-provided)
Error: [tsl] ERROR in /home/yui/happy-commit/src/github.ts(2,25)
      TS7016: Could not find a declaration file for module '@octokit/action'. '/home/yui/happy-commit/node_modules/@octokit/action/dist-node/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/octokit__action` if it exists or add a new declaration (.d.ts) file containing `declare module '@octokit/action';`
[tsl] ERROR in /home/yui/happy-commit/src/github.ts(95,28)
      TS7006: Parameter 'commit' implicitly has an 'any' type.
[tsl] ERROR in /home/yui/happy-commit/src/index.ts(3,25)
      TS7016: Could not find a declaration file for module '@octokit/action'. '/home/yui/happy-commit/node_modules/@octokit/action/dist-node/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/octokit__action` if it exists or add a new declaration (.d.ts) file containing `declare module '@octokit/action';`
    at /home/yui/happy-commit/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:1870077
    at /home/yui/happy-commit/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:37:383620
    at _done (eval at create (/home/yui/happy-commit/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:75523), <anonymous>:9:1)
    at eval (eval at create (/home/yui/happy-commit/node_modules/@vercel/ncc/dist/ncc/index.js.cache.js:20:75523), <anonymous>:34:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
I'll get right on it.

This is because of a breaking change in `npm@9` and our build system being deprecated.
