### ISSUE TITLE
[BUG]: v7 introduced a ProxyAgent that is not supported in Bun

### ISSUE THREAD

**Issue by rhuanbarreto** [octokit/action.js#641]
### What happened?

I received a package upgrade PR to bump this package to v7. ONe of the breaking changes is the addition to get a ProxyAgent.

But ProxyAgent from undici is not yet supported in Bun: https://github.com/oven-sh/bun/issues/4474

### Versions

Octokit.js v7.0.0
Bun latest version

### Relevant log output

```shell
SyntaxError: Import named 'ProxyAgent' not found in module 'undici'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
The `ProxyAgent` wasn't a breaking change as the proxy functionality was already there in previous versions of the package.

We simply updated to use undici as that is what powers Node's fetch API.

We don't guarantee support for other platforms than Node.

There isn't anything actionable on our side.
